# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoApp < Formula
  desc ""
  homepage "https://github.com/jrriehl/go-app"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.11/go-app_Darwin_arm64.tar.gz"
      sha256 "3ac3eebbb891d446e1f5d4a58fc85f3509df1f8f1df2452e903a4e2f39d1b7b2"

      def install
        bin.install "go-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.11/go-app_Darwin_x86_64.tar.gz"
      sha256 "a3f4e56932015fed1c2f457a9ed74cd574aa4091b7c86a7f3a86ca66dec8c35c"

      def install
        bin.install "go-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.11/go-app_Linux_arm64.tar.gz"
      sha256 "9bf83d117c9854ec43d14f69c4796709f332a2514d676333ba27396c2035d157"

      def install
        bin.install "go-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.11/go-app_Linux_x86_64.tar.gz"
      sha256 "4b08c58ae6cac05b170ba5d354a0ad6e9208338b7b00b101d97bc227df858bae"

      def install
        bin.install "go-app"
      end
    end
  end
end
