# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoApp < Formula
  desc ""
  homepage "https://github.com/jrriehl/go-app-bin"
  version "0.1.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.13/go-app-bin_Darwin_x86_64.tar.gz"
      sha256 "7e23930738e33f77cace50bb6255c453a6505e846b8097fb6c537cf7df20163d"

      def install
        bin.install "go-app-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.13/go-app-bin_Darwin_arm64.tar.gz"
      sha256 "0d495e62be9c0ddd35ee664e23be915e96cac23e3d1c4003ac19ec2a6df81817"

      def install
        bin.install "go-app-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.13/go-app-bin_Linux_x86_64.tar.gz"
      sha256 "5aaf8fcb008b928bddf2598ed9b5bb85eb49b1ae2accaad7806e672dc92e9853"

      def install
        bin.install "go-app-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.13/go-app-bin_Linux_arm64.tar.gz"
      sha256 "ca7b0767897a5f2bc5e66cd2d0ff7f45d1af3689c95e492aae9f548cc7b9ee94"

      def install
        bin.install "go-app-bin"
      end
    end
  end
end
