# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoApp < Formula
  desc ""
  homepage "https://github.com/jrriehl/go-app"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.8/go-app_Darwin_arm64.tar.gz"
      sha256 "7d235e7df00d0328fa120a452c996957c3e9d2c114e64e1bed2c98f594791119"

      def install
        bin.install "go-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.8/go-app_Darwin_x86_64.tar.gz"
      sha256 "7caa74b89799edd0e13bf0f459b8ee25e3fb9f0ad9d048debc5abb498fec3ada"

      def install
        bin.install "go-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.8/go-app_Linux_x86_64.tar.gz"
      sha256 "14e1072f002a03f3595e4976136dd096153e7635c4427fc1b1536b8cba3f3b2c"

      def install
        bin.install "go-app"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrriehl/go-app/releases/download/v0.1.8/go-app_Linux_arm64.tar.gz"
      sha256 "43a12019e0c7f7b32395f4f403d5b0062671fd98b8dd69dc53ff5625a4e5b184"

      def install
        bin.install "go-app"
      end
    end
  end
end
