# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoApp < Formula
  desc ""
  homepage "https://github.com/jrriehl/go-app-bin"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.15/go-app-bin_Darwin_arm64.tar.gz"
      sha256 "a4f9490eb0c21636264b78cfc3111d168ba972b4575ed67ab7b8ffd299b16773"

      def install
        bin.install "go-app-bin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.15/go-app-bin_Darwin_x86_64.tar.gz"
      sha256 "28e5c1028b277d2de31c4ac7c877d42d43494f9ae78249d31f7110948f6c7069"

      def install
        bin.install "go-app-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.15/go-app-bin_Linux_x86_64.tar.gz"
      sha256 "a29634cf5a4b441c831e1c10b4459a246f9990ac09ffbf3cc2c51979f3389baa"

      def install
        bin.install "go-app-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jrriehl/go-app-bin/releases/download/v0.1.15/go-app-bin_Linux_arm64.tar.gz"
      sha256 "bf6cd06db9de73450c93b35a7459a22f5d6ee051ecf676852cf1a9c8ae344511"

      def install
        bin.install "go-app-bin"
      end
    end
  end
end
